apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats
  labels:
    component: cats-webpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cats
      component: cats-webpage
  template:
    metadata:
      labels:
        app: cats
        component: cats-webpage
    spec:
      containers:
      - image: 171794051632.dkr.ecr.us-east-1.amazonaws.com/cat:v1
        name: cats
        ports:
        - containerPort: 80
