apiVersion: v1
kind: Pod
metadata:
  labels:
    run: dogs
  name: dogs
spec:
  containers:
  - image: 171794051632.dkr.ecr.us-east-1.amazonaws.com/dog:latest
    name: dogs
    ports:
    - containerPort: 80