apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cats
  labels:
    app: cats
    component: cats-webpage
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: cats
      component: cats-webpage
  template:
    metadata:
      labels:
        app: cats
        component: cats-webpage
    spec:
      containers:
      - image: 723154506924.dkr.ecr.us-east-1.amazonaws.com/cat:v1
        name: cats
        ports:
        - containerPort: 80
  