apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dogs
  labels:
    app: dogs
    component: dogs-webpage
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: dogs
      component: dogs-webpage
  template:
    metadata:
      labels:
        app: dogs
        component: dogs-webpage
    spec:
      containers:
      - image: 723154506924.dkr.ecr.us-east-1.amazonaws.com/dog:v1
        name: dogs
        ports:
        - containerPort: 80
  